### ISSUE TITLE
[Question] How did you open the addons menu when the app is first started? 

### ISSUE THREAD

**Issue by bboydflo** [jsonchin/highlight_tool#54]
I wonder how can I achieve the same. Thanks for putting this on github, but shouldn't be a manifest.json as well?

**Comment by jsonchin** [comment]
By app I assume you mean Google Docs.

[example google doc image](https://jsonchin.github.io/highlight_tool/images/use_case1.png)

On the same line below the title of the Google Doc there is a dropdown called "Add-ons".

If you're asking about how did I make the sidebar appear after clicking "Start" under "Highlight Tool",

https://github.com/jsonchin/highlight_tool/blob/master/src/Main.js
contains the code for the dropdown.

https://github.com/jsonchin/highlight_tool/blob/master/src/sidebar/SidebarBackend.js
contains the code for showing the sidebar.

I think the manifest.json should be kept private (it's actually appsscript.json from Google add-ons but the same idea) in the case I add private information to it.

**Comment by bboydflo** [comment]
After I installed the addon, it opened the addon menu in google docs and went directly to highlight tool item in the menu.

Thanks for the response, I will check the code again :D

**Comment by jsonchin** [comment]
Gotcha, I understand your question now.

I believe on installation, Google performs those steps to notify the user how to get to the add-on and any post-installation tips. The developer doesn't have any control over that.
